[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run start:full"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.variables]
NODE_ENV = "production"
DATABASE_URL = "file:./dev.db"
PORT = "3001"
